### ISSUE TITLE
Headers columns of dependency check table are reversed in Safari browser

### ISSUE THREAD

**Issue by jeanpierrefortune** [eclipse/keyple-website#122]
https://keyple.org/components-java/overview/dependency-check/

**Comment by mjawaaad** [comment]
Hey can you please elaborate this a little more so i can clearly understand the issue, as i am a beginner and want to work on this issue. Thank you

**Comment by andrei-cristea** [comment]
> Hey can you please assign this issue to me i think i can work on it. Thank you

Hello, thank you very much for your interest, but we have changed the display logic to improve the readability of the table. We will therefore close this issue.
